/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bp2proje;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Selin Sude ATALI
 */
public class Add_house extends javax.swing.JFrame {

    File file;
    String image_name, image_address;
    String image_name2, image_address2;
    File file2;
    String image_name3, image_address3;
    File file3;
    String username_a = "";
    int id_a = 0;

    public Add_house() {
        initComponents();
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        menu_clear = new javax.swing.JMenuItem();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        lbl_username = new javax.swing.JLabel();
        lbl_city = new javax.swing.JLabel();
        lbl_rooms = new javax.swing.JLabel();
        spinner_rooms = new javax.swing.JSpinner();
        lbl_for = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combobox_balcony = new javax.swing.JComboBox<>();
        lbl_cost = new javax.swing.JLabel();
        lbl_square = new javax.swing.JLabel();
        slider_square = new javax.swing.JSlider();
        lbl_furnishtype = new javax.swing.JLabel();
        combobox_furnishtype = new javax.swing.JComboBox<>();
        combobox_city = new javax.swing.JComboBox<>();
        txt_cost = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        lbl_squaretxt = new javax.swing.JLabel();
        radiobtn_rent = new javax.swing.JRadioButton();
        radiobtn_sale = new javax.swing.JRadioButton();
        btn_list = new javax.swing.JButton();
        txt_type = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lbl_first = new javax.swing.JLabel();
        lbl_second = new javax.swing.JLabel();
        lbl_third = new javax.swing.JLabel();

        menu_clear.setText("Clear");
        menu_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_clearActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menu_clear);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setMinimumSize(new java.awt.Dimension(800, 600));
        jSplitPane2.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setComponentPopupMenu(jPopupMenu1);
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 300));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 300));

        lbl_username.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbl_username.setText("Type");

        lbl_city.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbl_city.setText("City:");

        lbl_rooms.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbl_rooms.setText("Rooms:");

        spinner_rooms.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        lbl_for.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbl_for.setText("For:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Balcony:");

        combobox_balcony.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        lbl_cost.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbl_cost.setText("Cost:");

        lbl_square.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbl_square.setText("Square:");

        slider_square.setMaximum(200);
        slider_square.setValue(100);
        slider_square.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_squareStateChanged(evt);
            }
        });

        lbl_furnishtype.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbl_furnishtype.setText("Furnish Type:");

        combobox_furnishtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Furnished", "Unfurnished" }));

        combobox_city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ankara", "Antalya", "Bursa", "Çanakkale", "Edirne", "Eskişehir", "Gaziantep", "Giresun", "İstanbul", "İzmir", "Kütahya", "Mardin", "Muğla", "Rize", "Sakarya", "Trabzon", "Yalova" }));

        btn_add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiobtn_rent);
        radiobtn_rent.setText("Rent");

        buttonGroup1.add(radiobtn_sale);
        radiobtn_sale.setText("Sale");

        btn_list.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_list.setText("List");
        btn_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listActionPerformed(evt);
            }
        });

        txt_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apart", "Residence", "Villa" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btn_list, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_type, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(spinner_rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobox_balcony, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(lbl_square, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_squaretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(slider_square, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_city, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(combobox_city, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(radiobtn_rent, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_for, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(radiobtn_sale, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lbl_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(lbl_furnishtype, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combobox_furnishtype, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_type, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(spinner_rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combobox_balcony, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_square, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_squaretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slider_square, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_city, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(combobox_city, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(radiobtn_rent))
                    .addComponent(lbl_for, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radiobtn_sale)
                            .addComponent(lbl_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_furnishtype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combobox_furnishtype, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_list, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jSplitPane2.setTopComponent(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Photos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12))); // NOI18N
        jPanel4.setMinimumSize(new java.awt.Dimension(800, 300));
        jPanel4.setPreferredSize(new java.awt.Dimension(800, 300));

        lbl_first.setText("                            1.picture");
        lbl_first.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_first.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_firstMouseClicked(evt);
            }
        });

        lbl_second.setText("                            2.picture");
        lbl_second.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_secondMouseClicked(evt);
            }
        });

        lbl_third.setText("                               3.picture");
        lbl_third.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_thirdMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_first, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lbl_second, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(lbl_third, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_first, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_third, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_second, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel4);

        getContentPane().add(jSplitPane2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*Bu metodumda kullanıcı sliderın değerini değiştirdiğinde labelda o değeri gösteriyorum ve kullanıcı kaç metre girdiğini doğru 
    bir şekilde görebiliyor.
    
     */
    private void slider_squareStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_squareStateChanged
        // TODO add your handling code here:
        String value = String.valueOf(slider_square.getValue());
        lbl_squaretxt.setText(value);
    }//GEN-LAST:event_slider_squareStateChanged
    /* 3 tane label ekledim ve bu labellara tek tek tıklayınca görseli ilgili dosyadan alıp labellara kullanıcıya göstermek üzere kaydediyorum.
    Daha sonra seçili dosyayı database kaydedeceğim. 
     */

    private void lbl_firstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_firstMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int choose_i = chooser.showOpenDialog(this);
        if (choose_i == JFileChooser.APPROVE_OPTION) {
            file = chooser.getSelectedFile();
            image_name = file.getName();
            image_address = file.getPath();
            ImageIcon resim = new ImageIcon(image_address);
            lbl_first.setIcon(resim);
        }
    }//GEN-LAST:event_lbl_firstMouseClicked

    private void lbl_secondMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_secondMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser2 = new JFileChooser();
        int choose_i2 = chooser2.showOpenDialog(this);
        if (choose_i2 == JFileChooser.APPROVE_OPTION) {
            file2 = chooser2.getSelectedFile();
            image_name2 = file2.getName();
            image_address2 = file2.getPath();
            ImageIcon resim2 = new ImageIcon(image_address2);
            lbl_second.setIcon(resim2);
        }
    }//GEN-LAST:event_lbl_secondMouseClicked

    private void lbl_thirdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_thirdMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser3 = new JFileChooser();
        int choose_i3 = chooser3.showOpenDialog(this);
        if (choose_i3 == JFileChooser.APPROVE_OPTION) {
            file3 = chooser3.getSelectedFile();
            image_name3 = file3.getName();
            image_address3 = file3.getPath();
            ImageIcon resim3 = new ImageIcon(image_address3);
            lbl_third.setIcon(resim3);
        }

    }//GEN-LAST:event_lbl_thirdMouseClicked
    /*
    Burada ilk olarak database bağlamak için url,user ve passwordumu oluşturdum. Burada cost'u text fielda yazdığı için kullanıcı oraya
    sayı dışında bir karakter de yazabilirdi bunun kontrolünü sağlamak için bir regex yazdım.Eğer eşleşiyorsa house'da costa bu değeri kaydediyorum
    ama eğer eşleşme false ise cost değeri otomatik 0 döndüğünden dolayı database her türlü kaydetme yapıyordu ben de bunun olmasını istemediğim için 
    eğer cost!=0 a eşit değilse kayıt yapmasını istedim. Birçok yerde JoptionPane kullanarak ilgili duruma uygun olarak kullanıcılara hatayı
    belirtebiliyorum. Uygun şekilde frame den değerlerimi aldıktan ve kontrolleri sağladıktan sonra database kaydetme işlemini yapıyorum.
     */
    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:derby://localhost:1527/Records";
        String user = "Selin";
        String password = "123";
        String query = "INSERT INTO HOUSE(usernameid,username,type,city,rooms,balcony,square,furnished,forhouse,cost,photofirst,photosecond,photothird)"
                + "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)";
        House house = new House();
        int value = combobox_city.getSelectedIndex();
        int value_type = txt_type.getSelectedIndex();
        String pattern = "[0-9]+";
        String text = String.valueOf(txt_cost.getText());
        Pattern path = Pattern.compile(pattern);
        Matcher match = path.matcher(text);
        if (match.matches() == true) {
            int cost = Integer.parseInt(txt_cost.getText());
            house.cost = cost;
        } else {
            JOptionPane.showMessageDialog(null, "Please enter cost.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }
        house.usernameid = id_a;

        house.username = username_a;
        house.type = txt_type.getItemAt(value_type);
        house.city = combobox_city.getItemAt(value);
        int room = (int) spinner_rooms.getValue();
        int balcony = combobox_balcony.getSelectedIndex();
        if (combobox_balcony.getItemAt(balcony) == "Yes") {
            house.balcony = true;
        } else {
            house.balcony = false;
        }
        house.rooms = room;
        int deger = slider_square.getValue();
        house.square = deger;
        int furnish_type = combobox_furnishtype.getSelectedIndex();
        if (combobox_furnishtype.getItemAt(furnish_type) == "Furnished") {
            house.furnished = true;
        } else {
            house.furnished = false;
        }
        if (radiobtn_rent.isSelected()) {
            house.forhouse = radiobtn_rent.getText();
        } else {
            house.forhouse = radiobtn_sale.getText();
        }

        if (house.username != "" && house.cost != 0) {
            try {
                Connection conn = DriverManager.getConnection(url, user, password);
                FileInputStream fis = new FileInputStream(file);
                FileInputStream fis2 = new FileInputStream(file2);
                FileInputStream fis3 = new FileInputStream(file3);
                PreparedStatement ps = conn.prepareStatement(query);
                ps.setInt(1, house.usernameid);
                ps.setString(2, house.username);
                ps.setString(3, house.type);
                ps.setString(4, house.city);
                ps.setInt(5, house.rooms);
                ps.setBoolean(6, house.balcony);
                ps.setInt(7, house.square);
                ps.setBoolean(8, house.furnished);
                ps.setString(9, house.forhouse);
                ps.setDouble(10, house.cost);
                ps.setBlob(11, fis);
                ps.setBlob(12, fis2);
                ps.setBlob(13, fis3);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "House added to the system.", "Information", JOptionPane.INFORMATION_MESSAGE);
                ps.close();
                fis.close();
                conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Failed to Register.", "Warning", JOptionPane.INFORMATION_MESSAGE);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "File not find. ", "Warning", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Operation failed.", "Warning", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_btn_addActionPerformed
    /*
    Burada eğer kullanıcı eklediği evleri görmek isterse ilgili frame çağırıyorum. List frame'imdeki username'e kullanıcınn username'ini ekliyorum.
    Çünkü List frame'imde sadece emlakçının kendi evlerini listeliyorum.Show_house metodumda kullanabilmek için loginden çektiğim username'i -sınavda da 
    kullandığım şekilde- buraya aktarıyorum.
    setLocationRelativeTo işlemini kullanarak açılacak olan frame'in ekran ortasında açılmasını sağlıyorum.
     */
    private void btn_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listActionPerformed
        // TODO add your handling code here:
        List list = new List();
        list.username_list = username_a;
        list.show_house();
        list.setLocationRelativeTo(null);
        list.setVisible(true);
    }//GEN-LAST:event_btn_listActionPerformed
    /*
    Burada popup'a eklediğim jMenuItem1 ile eğer kullanıcı tekrar bir ev girmek isterse tek bir tuşla ekranda var olan bütün değerleri 
    temizliyorum ve kullanıcıya kolaylık sağlamış olabiliyorum.
     */
    private void menu_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_clearActionPerformed
        // TODO add your handling code here:
        txt_cost.setText("");
        txt_type.setSelectedIndex(0);
        spinner_rooms.setValue(0);
        combobox_balcony.setSelectedIndex(1);
        slider_square.setValue(0);
        combobox_city.setSelectedIndex(0);
        radiobtn_rent.setSelected(false);
        radiobtn_sale.setSelected(false);
        combobox_furnishtype.setSelectedIndex(0);
        lbl_first.setIcon(null);
        lbl_second.setIcon(null);
        lbl_third.setIcon(null);


    }//GEN-LAST:event_menu_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_house.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_house.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_house.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_house.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_house().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_list;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combobox_balcony;
    private javax.swing.JComboBox<String> combobox_city;
    private javax.swing.JComboBox<String> combobox_furnishtype;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel lbl_city;
    private javax.swing.JLabel lbl_cost;
    private javax.swing.JLabel lbl_first;
    private javax.swing.JLabel lbl_for;
    private javax.swing.JLabel lbl_furnishtype;
    private javax.swing.JLabel lbl_rooms;
    private javax.swing.JLabel lbl_second;
    private javax.swing.JLabel lbl_square;
    private javax.swing.JLabel lbl_squaretxt;
    private javax.swing.JLabel lbl_third;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JMenuItem menu_clear;
    private javax.swing.JRadioButton radiobtn_rent;
    private javax.swing.JRadioButton radiobtn_sale;
    private javax.swing.JSlider slider_square;
    private javax.swing.JSpinner spinner_rooms;
    private javax.swing.JTextField txt_cost;
    private javax.swing.JComboBox<String> txt_type;
    // End of variables declaration//GEN-END:variables
}
