/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bp2proje;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Selin Sude ATALI
 */
public class Settings extends javax.swing.JFrame {

    String type = "";
    String username = "";
    int id = 0;

    /*
    SetResizable(false) kullanarak panelimin olduğu boyutta kalmasını,maksimum hale getirilememesini sağlıyorum.
     */
    public Settings() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menu_goback = new javax.swing.JMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JButton();
        btn_changeusername = new javax.swing.JButton();
        btn_changepassword = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ImageIcon icon=new ImageIcon(getClass().getResource("bluebacckground.jpg"));Image img=icon.getImage();
        jDesktopPane2 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(img,0,0,getWidth(),
                    getHeight(),this);
            }
        };

        menu_goback.setText("Go back");
        menu_goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_gobackActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menu_goback);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 520));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setComponentPopupMenu(jPopupMenu1);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(600, 400));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(600, 400));

        jPanel2.setMinimumSize(new java.awt.Dimension(600, 150));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 150));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_images/log-out.png"))); // NOI18N
        btn_logout.setText("Log out");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel2.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 40));

        btn_changeusername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_images/writing.png"))); // NOI18N
        btn_changeusername.setText("Change Username");
        btn_changeusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changeusernameActionPerformed(evt);
            }
        });
        jPanel2.add(btn_changeusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, 40));

        btn_changepassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_images/reset-password.png"))); // NOI18N
        btn_changepassword.setText("Change Password");
        btn_changepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changepasswordActionPerformed(evt);
            }
        });
        jPanel2.add(btn_changepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bp2proje/bluebacckground.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMinimumSize(new java.awt.Dimension(600, 150));
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 150));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 150));

        jSplitPane1.setTopComponent(jPanel2);

        jDesktopPane2.setMinimumSize(new java.awt.Dimension(600, 370));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jDesktopPane2);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    Eğer kişi log out butonuna tıklarsa Are you sure to quit diye soruyorum.Seçtiği seçeneğe göre işlemi gerçekleştiriyorum.
     */
    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        int value = JOptionPane.showConfirmDialog(null, "Are you sure to quit?", "Warning!", JOptionPane.YES_NO_OPTION);
        if (value == 0) {
            this.dispose();
            Login login = new Login();
            login.setLocationRelativeTo(null);
            login.setVisible(true);
        } else if (value == 1) {
            JOptionPane.showMessageDialog(null, "Okey you are here.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btn_logoutActionPerformed
    /*
    Change_username frame'ini açıyorum.Change_username internal frame olduğundan ve main metodu olmadığından bunu öncelikle 
    jDesktopPane2'ya ekliyorum.
     */
    private void btn_changeusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changeusernameActionPerformed
        // TODO add your handling code here:
        Change_username change_username = new Change_username();
        jDesktopPane2.add(change_username);
        change_username.id = id;
        change_username.username = username;
        change_username.setVisible(true);

    }//GEN-LAST:event_btn_changeusernameActionPerformed
    /*
    Change_password frame'ini açıyorum.Change_password internal frame olduğundan ve main metodu olmadığından bunu öncelikle 
    jDesktopPane2'ya ekliyorum.
     */
    private void btn_changepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changepasswordActionPerformed
        // TODO add your handling code here:
        Change_password change_password = new Change_password();
        jDesktopPane2.add(change_password);
        change_password.username = username;
        change_password.setVisible(true);

    }//GEN-LAST:event_btn_changepasswordActionPerformed
    /*
    Kullanıcı eğer popup menude goback'i seçtiğinde  kullanıcının type'ına göre uygun frame açıyorum.
     */
    private void menu_gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_gobackActionPerformed
        // TODO add your handling code here:
        if (type.equals("Client")) {
            Home_client home = new Home_client();
            home.id = id;
            home.type = type;
            home.username_h = username;
            this.dispose();
            home.setVisible(true);
        } else {
            Home home = new Home();
            home.id = id;
            home.type = type;
            home.username_h = username;
            this.dispose();
            home.setVisible(true);
        }
    }//GEN-LAST:event_menu_gobackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Settings settings = new Settings();
                settings.setLocationRelativeTo(null);
                settings.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_changepassword;
    private javax.swing.JButton btn_changeusername;
    private javax.swing.JButton btn_logout;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenuItem menu_goback;
    // End of variables declaration//GEN-END:variables
}
