/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bp2proje;

import java.sql.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Random;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Selin Sude ATALI
 */
public class Update_house extends javax.swing.JFrame {

    String username_a = "";
    int id_a = 0;
    String type = "";
    String city = "";
    int rooms = 0;
    String for_house = "";
    boolean balcony = false;
    String cost = null;
    int square = 0;
    boolean furnish_type = false;
    ImageIcon imageicon;
    ImageIcon imageicon2;
    ImageIcon imageicon3;

    /*
    SetResizable(false) kullanarak panelimin olduğu boyutta kalmasını,maksimum hale getirilememesini sağlıyorum.
     */
    public Update_house() {
        initComponents();
        setResizable(false);

    }

    /*
    Burada emlakçının listte güncellemek için seçtiği evin bilgilerini ekrandaki uygun yerlerde göstereceğim metodumu çağırıyorum.
    Bu metodu Image_showestate 'de çağırıyorum ve ekranda gösterilecek bilgilerimi kaydediyorum.
     */
    public void Update() {
        for (int i = 0; i < txt_type.getItemCount(); i++) {
            if (txt_type.getItemAt(i).equals(type)) {
                txt_type.setSelectedIndex(i);
            }
        }
        for (int j = 0; j < combobox_city.getItemCount(); j++) {
            if (city.equals(combobox_city.getItemAt(j))) {
                combobox_city.setSelectedIndex(j);
            }
        }
        spinner_rooms.setValue(rooms);
        if (for_house.equals("Rent")) {
            radiobtn_rent.setSelected(true);

        } else {
            radiobtn_sale.setSelected(true);
        }
        if (balcony == true) {
            combobox_balcony.setSelectedIndex(0);
        } else {
            combobox_balcony.setSelectedIndex(1);
        }
        txt_cost.setText(cost);
        if (furnish_type == true) {
            combobox_furnishtype.setSelectedIndex(0);
        } else {
            combobox_furnishtype.setSelectedIndex(1);
        }
        lbl_first.setIcon(imageicon);
        lbl_second.setIcon(imageicon2);
        lbl_third.setIcon(imageicon3);
        slider_square.setValue(square);
        String value = String.valueOf(slider_square.getValue());
        lbl_squaretxt.setText(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        lbl_username = new javax.swing.JLabel();
        lbl_city = new javax.swing.JLabel();
        lbl_rooms = new javax.swing.JLabel();
        spinner_rooms = new javax.swing.JSpinner();
        lbl_for = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combobox_balcony = new javax.swing.JComboBox<>();
        lbl_cost = new javax.swing.JLabel();
        lbl_square = new javax.swing.JLabel();
        slider_square = new javax.swing.JSlider();
        lbl_furnishtype = new javax.swing.JLabel();
        combobox_furnishtype = new javax.swing.JComboBox<>();
        combobox_city = new javax.swing.JComboBox<>();
        txt_cost = new javax.swing.JTextField();
        lbl_squaretxt = new javax.swing.JLabel();
        radiobtn_rent = new javax.swing.JRadioButton();
        radiobtn_sale = new javax.swing.JRadioButton();
        txt_type = new javax.swing.JComboBox<>();
        btn_update = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbl_first = new javax.swing.JLabel();
        lbl_second = new javax.swing.JLabel();
        lbl_third = new javax.swing.JLabel();

        jMenuItem1.setText("Clear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setMinimumSize(new java.awt.Dimension(800, 600));
        jSplitPane2.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setComponentPopupMenu(jPopupMenu1);
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 300));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 300));

        lbl_username.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbl_username.setText("Type");

        lbl_city.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbl_city.setText("City:");

        lbl_rooms.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbl_rooms.setText("Rooms:");

        spinner_rooms.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        lbl_for.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbl_for.setText("For:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Balcony:");

        combobox_balcony.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        lbl_cost.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbl_cost.setText("Cost:");

        lbl_square.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbl_square.setText("Square:");

        slider_square.setMaximum(200);
        slider_square.setValue(100);
        slider_square.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_squareStateChanged(evt);
            }
        });

        lbl_furnishtype.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbl_furnishtype.setText("Furnish Type:");

        combobox_furnishtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Furnished", "Unfurnished" }));

        combobox_city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ankara", "Antalya", "Bursa", "Çanakkale", "Edirne", "Eskişehir", "Gaziantep", "Giresun", "İstanbul", "İzmir", "Kütahya", "Mardin", "Muğla", "Rize", "Sakarya", "Trabzon", "Yalova" }));

        buttonGroup1.add(radiobtn_rent);
        radiobtn_rent.setText("Rent");

        buttonGroup1.add(radiobtn_sale);
        radiobtn_sale.setText("Sale");

        txt_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apart", "Residence", "Villa" }));

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_city, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(combobox_city, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(radiobtn_rent, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_for, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(radiobtn_sale, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_update)
                                .addGap(178, 178, 178))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(lbl_furnishtype, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combobox_furnishtype, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_type, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(spinner_rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobox_balcony, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(lbl_square, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_squaretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(slider_square, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_type, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(spinner_rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combobox_balcony, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_square, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_squaretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slider_square, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_city, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(combobox_city, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(radiobtn_rent))
                    .addComponent(lbl_for, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radiobtn_sale)
                            .addComponent(lbl_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_furnishtype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combobox_furnishtype, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(btn_update)
                .addContainerGap())
        );

        jSplitPane2.setTopComponent(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Photos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12))); // NOI18N
        jPanel4.setMinimumSize(new java.awt.Dimension(800, 300));
        jPanel4.setPreferredSize(new java.awt.Dimension(800, 300));

        lbl_first.setText("                            1.picture");
        lbl_first.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_second.setText("                            2.picture");

        lbl_third.setText("                               3.picture");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_first, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lbl_second, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(lbl_third, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_first, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_third, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_second, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel4);

        getContentPane().add(jSplitPane2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*Bu metodumda kullanıcı sliderın değerini değiştirdiğinde labelda o değeri gösteriyorum ve kullanıcı kaç metre girdiğini doğru 
    bir şekilde görebiliyor.
    
     */
    private void slider_squareStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_squareStateChanged
        // TODO add your handling code here:
        String value = String.valueOf(slider_square.getValue());
        lbl_squaretxt.setText(value);
    }//GEN-LAST:event_slider_squareStateChanged
    /*
    Popup menu ekledim. Clear menu item'ı ile ekrandaki bütün textleri "" olarak diğerlerini ise belirlediğim default pozisyonlarına alıyorum.
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        txt_cost.setText("");
        txt_type.setSelectedIndex(0);
        spinner_rooms.setValue(0);
        combobox_balcony.setSelectedIndex(1);
        slider_square.setValue(0);
        combobox_city.setSelectedIndex(0);
        radiobtn_rent.setSelected(false);
        radiobtn_sale.setSelected(false);
        combobox_furnishtype.setSelectedIndex(0);

    }//GEN-LAST:event_jMenuItem1ActionPerformed
    /*
    Eğer kullanıcı update butonuna basarsa önceki fotoğraflar hariç hepsini güncelleyebiliyor.House'dan bir nesne oluşturarak bilgilerimi ilgili
    variablelara kaydediyorum ve database'imde ilgili house'ın id'sindeki satırı güncelliyorum.
     */
    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:derby://localhost:1527/Records";
        String user = "Selin";
        String password = "123";
        House house = new House();
        int value = combobox_city.getSelectedIndex();
        int value_type = txt_type.getSelectedIndex();
        house.username = username_a;
        house.type = txt_type.getItemAt(value_type);
        house.city = combobox_city.getItemAt(value);
        int room = (int) spinner_rooms.getValue();
        int balcony = combobox_balcony.getSelectedIndex();
        if (combobox_balcony.getItemAt(balcony) == "Yes") {
            house.balcony = true;
        } else {
            house.balcony = false;
        }
        house.rooms = room;
        int deger = slider_square.getValue();
        house.square = deger;
        int furnish_type = combobox_furnishtype.getSelectedIndex();
        if (combobox_furnishtype.getItemAt(furnish_type) == "Furnished") {
            house.furnished = true;
        } else {
            house.furnished = false;
        }
        if (radiobtn_rent.isSelected()) {
            house.forhouse = radiobtn_rent.getText();
        } else {
            house.forhouse = radiobtn_sale.getText();
        }
        double cost = Double.parseDouble(txt_cost.getText());
        house.cost = cost;
        String query = "UPDATE house set type=?,city=?,rooms=?,balcony=?,square=?,furnished=?,forhouse=?,cost=? where id =" + id_a;

        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, house.type);
            ps.setString(2, house.city);
            ps.setInt(3, house.rooms);
            ps.setBoolean(4, house.balcony);
            ps.setInt(5, house.square);
            ps.setBoolean(6, house.furnished);
            ps.setString(7, house.forhouse);
            ps.setDouble(8, house.cost);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Update correctly", "Information", JOptionPane.INFORMATION_MESSAGE);
            ps.close();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Update_house.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_house.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_house.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_house.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_house.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_house().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combobox_balcony;
    private javax.swing.JComboBox<String> combobox_city;
    private javax.swing.JComboBox<String> combobox_furnishtype;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel lbl_city;
    private javax.swing.JLabel lbl_cost;
    private javax.swing.JLabel lbl_first;
    private javax.swing.JLabel lbl_for;
    private javax.swing.JLabel lbl_furnishtype;
    private javax.swing.JLabel lbl_rooms;
    private javax.swing.JLabel lbl_second;
    private javax.swing.JLabel lbl_square;
    private javax.swing.JLabel lbl_squaretxt;
    private javax.swing.JLabel lbl_third;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JRadioButton radiobtn_rent;
    private javax.swing.JRadioButton radiobtn_sale;
    private javax.swing.JSlider slider_square;
    private javax.swing.JSpinner spinner_rooms;
    private javax.swing.JTextField txt_cost;
    private javax.swing.JComboBox<String> txt_type;
    // End of variables declaration//GEN-END:variables
}
